### ISSUE TITLE
Scripts come out looking odd.

### ISSUE THREAD

**Issue by brenicus** [SamboyCoding/AudicaShredder#70]
Whenever i get the .dll's and open them, they never come out normal. For example, https://pastebin.com/1h7hKJKA. And while extracting them, I get this error https://pastebin.com/2JvHEeww at 80% before the script ends.

**Comment by SamboyCoding** [comment]
The script is looking as expected and the error is a known one. 

If you don't know why the script looks the way it does, I recommend reading the readme here on github. 

The error is specifically marked as a warning (and so, almost certainly came up in yellow in your console) because it only affects that one method.
